### PR TITLE
Add swift package index yml config file

### PR DESCRIPTION
**Pull request by rizwankce**
for auto generating DocC from SPI

### CODE REVIEW

**Comment by rizwankce** [comment]
Im just following the steps from [this link](https://blog.swiftpackageindex.com/posts/auto-generating-auto-hosting-and-auto-updating-docc-documentation/)

We will get Documentation link in SPI along with free hosted Documentations. I don't know how I can test this out

**Comment by icanzilb** [comment]
Great @rizwankce the docs are up! https://swiftpackageindex.com/MarkCodable/MarkCodable/0.6.7/documentation/markcodable

**Comment by rizwankce** [comment]
> Great @rizwankce the docs are up! https://swiftpackageindex.com/MarkCodable/MarkCodable/0.6.7/documentation/markcodable

Yup. Glad it worked in first try. 

Still can't get iOS platform build on SPI.

**Comment by icanzilb** [comment]
We'll figure it out, if not — we'll ping Sven from SPI to double-check

**Pull request merged**
