### PR TITLE
Update CI with Xcode 15 and Swift 5.9

### PR DESCRIPTION
**Pull request by rizwankce**

### CODE REVIEW

**Review by icanzilb — APPROVED** [review]

**Comment by rizwankce** [comment]
@icanzilb this was quick to review. I don't have merge permission. If this looks good for you. We can merge it.

**Comment by icanzilb** [comment]
@rizwankce sure thing, thanks for the PR 🎉

**Comment by rizwankce** [comment]
@icanzilb If you are okay, can you add `hacktoberfest-accepted` label?. So that It can count for me.

**Comment by icanzilb** [comment]
Sure thing, much appreciated you spotted this and fixed it

**Pull request merged**
